### ISSUE TITLE
Initialiazing files management failes with kernel panic

### ISSUE THREAD

**Issue by Weselton** [llenotre/maestro#14]
After `cargo build` i get kernel panic:
![Снимок экрана от 2024-01-14 19-59-39](https://github.com/llenotre/maestro/assets/31829264/b09725a6-aaf7-49b5-9994-8fb7a3b64cfb)

My OS: Fedora Linux 39 (Workstation Edition) x86_64

**Comment by llenotre** [comment]
Hello!

Did you insert a disk in your virtual machine before testing?
You need to have a disk to boot on, with a filesystem (ext2) and programs on it to have a working system.

**Comment by Sovenok-Hacker** [comment]
@llenotre Add this to FAQ on the main page, I think it will be very popular problem ;)

**Comment by llenotre** [comment]
I think that would be relevant yes! I will do it.

If you want to test the OS easily, I made an ISO file with an installer available on my [blog](https://blog.lenot.re). You can download it [here](https://github.com/llenotre/maestro-install/).

There are also instructions to build the installer [here](https://github.com/llenotre/maestro-install).

**Comment by Weselton** [comment]
> Hello!
> 
> Did you insert a disk in your virtual machine before testing? You need to have a disk to boot on, with a filesystem (ext2) and programs on it to have a working system.

Thanks, this helped me! I was inattentive
