### ISSUE TITLE
Error when attempting to build

### ISSUE THREAD

**Issue by pixlxip** [llenotre/maestro#30]
```
error: command failed: 'cargo': Permission denied (os error 13)
```

This is shown when trying to build with `cargo build`. `cargo build` works on my own projects, but when attempting to build maestro, this error is displayed.

System info:
Vanilla OS 2.0 Beta (commands being run is an apx-vso-pica container)
cargo 1.78.0 (54d8815d0 2024-03-26) (installed from rustup)
linux 6.7.9-amd64

**Comment by llenotre** [comment]
Hi and thank you for the report!

I believe this most likely comes from the build script (`build.rs` and the `build_impl` directory)

The build script had been partially re-written on the [cleanup](https://github.com/llenotre/maestro/pull/17) branch and the problem may have already been fixed.
I will recheck when I have the bandwidth to do so.

Have a good day!

**Comment by pixlxip** [comment]
I will try later, thanks for telling me!

**Comment by pixlxip** [comment]
This starts to build, but it seems like there is no Cargo.toml in the cleanup branch. Can I safely copy it over from main?

```
> cargo build
info: syncing channel updates for 'nightly-2024-03-16-x86_64-unknown-linux-gnu'
info: latest update on 2024-03-16, rust version 1.78.0-nightly (c67326b06 2024-03-15)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'miri'
info: downloading component 'rust-src'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustc-dev'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'miri'
info: installing component 'rust-src'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustc-dev'
info: installing component 'rustfmt'
error: could not find `Cargo.toml` in `/home/pixl_xip/Projects/Git/maestro` or any parent directory
```

**Comment by pixlxip** [comment]
I will actually close this issue (it's solved) and create a new one, to avoid confusion if somebody experiences the same issue as me.
