### ISSUE TITLE
error: linker `i686-elf-ld` not found

### ISSUE THREAD

**Issue by pixlxip** [llenotre/maestro#31]
When trying to build the kernel using `cargo build` in the `cleanup` branch, I get this error:

```
> cargo build
   Compiling maestro v0.1.0 (/home/pixl_xip/Projects/Git/maestro/kernel)
warning: maestro@0.1.0: Compiler version doesn't include clang or GCC: "cc" "--version"
error: linker `i686-elf-ld` not found
  |
  = note: No such file or directory (os error 2)

The following warnings were emitted during compilation:

warning: maestro@0.1.0: Compiler version doesn't include clang or GCC: "cc" "--version"

error: could not compile `maestro` (lib) due to 1 previous error
```

My system:
cargo 1.78.0-nightly (7065f0ef4 2024-03-12)
gcc (Debian 13.2.0-23) 13.2.0
GNU ld (GNU Binutils for Debian) 2.42
linux 6.7.9-amd64
Vanilla OS 2.0 x86_64 with subsystem apx-vso-pico (Debian based)

**Comment by llenotre** [comment]
Hi,

You need to have the `i686-elf-ld` command to compile the kernel.
This is not currently documented (which is an issue).

You can probably install it using a package manager, or else you can compile it using [this repo](https://github.com/llenotre/cross_gcc_builder) which is dirty and will be replaced someday.

**Comment by pixlxip** [comment]
I tried `sudo apt install i686-elf-ld` but `apt` said that it wasn't found. I successfully built it from your repo, and navigating back to and building maestro was successful. Thank you.
